
//todo list
//retrieve todo's from localStorage.Retun an empty array if no list is found
//localStorage are key/valye pairs and always stored as strings. Always parse them
//to a valid JS object before using them
function get_todos(){
    var todos = [];
    var todos_str = localStorage.getItem('todo');
    if(todos_str !=null){
        todos = JSON.parse(todos_str);
    }
    return todos;
}
// Adding a new TODO entry
function add(){
    var todos = get_todos();
    var task = $('#task').val();
    var taskObj = {};
    taskObj.task = task;
    taskObj.isDone = false;
    todos.push(taskObj);
    localStorage.setItem('todo',JSON.stringify(todos));
    //update list of the TODO's displayed on webpage
    show();
    $("input").val("");
    //avoid any further actions generated by 'click' event
    return false;
}

//remove the to-do list items from localStorage
function removeStorage(){
    var todos = get_todos();    
    var id = event.currentTarget.getAttribute('id');
        todos.splice(id,1);
    localStorage.setItem('todo',JSON.stringify(todos));
    show();
    return false;
}

//update localStorage
function updateLocalStorage(val){
    
     var todos = get_todos();
        for(var i=0;i<todos.length;i++){
            if(todos[i].task === val){
                    todos[i].isDone = true;
            }
        }
    localStorage.setItem('todo',JSON.stringify(todos));
    
}

//display th current todo list stored in the LocalStorage
function show(){

    var todos = get_todos();
    var html="<ul>";
    for(var i=0; i<todos.length; i++) {
        var addClassStr = todos[i].isDone ? 'class=taskCompleted' : '';
        html+= '<li ' + addClassStr + ' value='+ todos[i].task + '>' + todos[i].task + '<button class="remove" id="' + i  + '">x</button></li>';
    }
    html+="</ul>";
    $("#todos").html(html);
    $(".remove").click(function(event){
        event.currentTarget.parentElement.remove();
        removeStorage();        
    }); 
    
    $("#todos").on('click','li',function(){
        $(this).addClass("taskCompleted");
        updateLocalStorage($(this).attr("value"));

    });


}

$("input").keydown(function(e){
    if(e.keyCode===13){
        event.preventDefault();
        add();    
    }
});


$(".todo-bar").hide();
$(".cross").hide();
    $(".hamburger").click(()=>{
    $(".todo-bar").slideToggle( "slow", ()=> {
        $( ".hamburger" ).hide();
        $( ".cross" ).show();
        });
    });
   $(".cross").click(()=>{
       $(".todo-bar").slideToggle("slow",()=>{
           $(".cross").hide();
           $(".hamburger").show();
        });
   });

   $("#todos").on('click','li',function(){
    $(this).addClass("taskCompleted");
});
$("#days").click(()=>{
    $(".todo-bar").slideToggle( "slow", ()=> {
        $( ".hamburger" ).hide();
        $( ".cross" ).show();
        });
        $(".hamburger").show();   
});
  
   
show();